version: '3.2'
services:
  # FRONT
  chronograf:
    # Full tag list: https://hub.docker.com/r/library/chronograf/tags/
    image: chronograf:alpine
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    volumes:
      # Mount for chronograf database
      - chronograf-data:/var/lib/chronograf
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8888:8888"
    networks:
      - influx
    depends_on:
      - kapacitor
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - KAPACITOR_URL=http://kapacitor:9092
  # MIDDLE
  kapacitor:
    # Full tag list: https://hub.docker.com/r/library/kapacitor/tags/
    image: kapacitor:alpine
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    secrets:
      - kapacitor.conf
    volumes:
      # Mount for kapacitor data directory
      - kapacitor-data:/var/lib/kapacitor
      # Mount for kapacitor configuration
      #- /etc/kapacitor/config:/etc/kapacitor
    ports:
      # The API for Kapacitor is served on port 9092
      - "9092:9092"
    networks:
      - influx
    entrypoint:
      - kapacitord
      - -config
      - /run/secrets/kapacitor.conf
    # Kapacitor requires network access to Influxdb
    depends_on:
      - influxdb
  # BACK
  telegraf:
    # Full tag list: https://hub.docker.com/r/library/telegraf/tags/
    image: telegraf:alpine
    environment:
      HOSTNAME: "{{.Node.Hostname}}"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    secrets:
      - telegraf.conf
    volumes:
      # Mount for telegraf configuration
      #- /etc/telegraf:/etc/telegraf
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock
      #- /var/run/utmp:/var/run/utmp:ro
    networks:
      - influx
    depends_on:
      - influxdb
    entrypoint:
      - telegraf
      - -config
      - /run/secrets/telegraf.conf
  # DATABASE
  influxdb:
    # Full tag list: https://hub.docker.com/r/library/influxdb/tags/
    image: influxdb:alpine
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    secrets:
      - influxdb.conf
    volumes:
      # Mount for influxdb data directory
      - influxdb-data:/var/lib/influxdb
      # Mount for influxdb configuration
      #- /etc/influxdb/config:/etc/influxdb
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
    networks:
      - influx
    entrypoint:
      - influxd
      - -config
      - /run/secrets/influxdb.conf
networks:
  influx:

volumes:
  chronograf-data:
  kapacitor-data:
  influxdb-data:

secrets:
  influxdb.conf:
    file: ./influxdb.conf
  kapacitor.conf:
    file: ./kapacitor.conf
  telegraf.conf:
    file: ./telegraf.conf

